server:
  port: 8081

spring:
  application:
    name: configuration-service
  datasource:
    url: jdbc:h2:file:./data/configuration-db
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
