server:
  port: 8083
spring:
  application:
    name: fluid-analysis-service
services:
  analysis-management:
    url: ${ANALYSIS_MANAGEMENT_SERVICE_URL:http://localhost:8082}
  next:
    url: ${THERMAL_ANALYSIS_SERVICE_URL:http://localhost:8084}
resilience4j:
  circuitbreaker:
    instances:
      nextService:
        sliding-window-size: 5
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
management:
  endpoints:
    web:
      exposure:
        include: health,info
